---
title: "conceptual_figure"
author: "em"
date: "September 24, 2018"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('~/Documents/qpc-maize/')
library(MASS)
library(quaint)
library(LaCroixColoR)

myBound = function(x){
if (x>1) {x=1}
if (x<0) {x=0}
  return(x)
}

calcVa = function (afs, betas) 
{
    return(sum(2 * afs * (1 - afs) * (betas^2)))
}

getPopGenos <- function(p, pops, popSize){ #turns allele frequencies into individual genotypes, p is row, pops is the matrix of frequencies, popSize is the # of individuals per pop
  indFreqs = t(matrix(rep(pops[p,],popSize),nrow=nloci,ncol=popSize))
  popGenos = apply(indFreqs,c(1,2),function(x){sum(sample(c(1,0),2,replace=TRUE, prob = c(x,1-x)))})
  return(popGenos)
}

getPopPhenos <- function(pg,b){
  pp = lapply(pg, function(x){x %*% b}) 
  return(pp)}

getBetas <- function(res, colu, loci){  #get betas including 0s that weren't tested
  labs = data.frame(1:loci)
  names(labs) = 'lab'
  res$lab = as.numeric(substr(res$rs, 3, 100))
  allB = merge(labs,res, by="lab", all=TRUE)
  betas = allB[,colu]
  betas[is.na(betas)] <- 0
  return(betas)
}

```


```{r twopops, echo=F, eval=F}

i=1
x1 <- runif(1) #getting a random number so there's a seed
save(".Random.seed", file=paste("data/figure_sims/randomSeed.",i, sep=""))

Faa = 0.15

#we want 100 individuals, 50 in each pop, so sigma is...
#sigma = matrix(0,nrow=100, ncol=100)
#sigma[1:50,1:50] = matrix(Faa, nrow=50,ncol=50)
#sigma[51:100,51:100] = matrix(Faa, nrow=50,ncol=50)
#diag(sigma) = 0.3
sigma = matrix(c(Faa,0,0,Faa),nrow=2, ncol=2)


#simulate allele freqs in two pops at these loci
nloci = 500
ancPop = runif(nloci, min=0, max=1)
presentPops1 = sapply(ancPop, function(x){mvrnorm(n=1, mu = rep(x,2), x*(1-x)*sigma)})
presentPops = apply(presentPops1, c(1,2), myBound) #deal with numbers greater or less than 0 (the outer bounds are sticky)

#plot(ancPop, bty='n', xlab = "locus", ylab = "p")
#sapply(1:100, function(x){lines(c(x,x), c(presentPops[1,x], presentPops[2,x]))})

#get the population genotypes
npop = 50
popGenos = lapply(1:2, function(x) getPopGenos(x, presentPops, npop)) #a list of 2 elements, each is a population

#make a kinship matrix
myG = rbind(popGenos[[1]], popGenos[[2]])/2
myK = make_k(myG)
heatmap(myK)

myEig = eigen(myK)

mycol = lacroix_palette('Mango')[1:4]
plot(1:50,myEig$values[1:50])
plot(myEig$vectors[,1], myEig$vectors[,2], col = c(rep(mycol[1], 50),rep(mycol[2], 50)), bty='n', xlab= 'PC1', ylab = 'PC2', lwd=2, xlim = c(-.2, .2))
legend('topright', c('pop1','pop2'), bty="n", pch=1, pt.lwd=2, col = mycol)


beetas = matrix(c(rnorm(nloci)), ncol=1, nrow=nloci) #half are 0, half are from a normal distribution

#if (opt$environmental_shift == TRUE){pop.phenos = myShift(pop.phenos)}

#individual noise shifts
popPhenos = getPopPhenos(popGenos, beetas)
popPhenosNoise = lapply(popPhenos, function(x){x + rnorm(length(x), mean=0, sd=sd(x)/2 )})

#plot(popPhenos[[1]], popPhenosNoise[[1]])


myPhenos = unlist(popPhenosNoise)
plot(myEig$vectors[,1], myPhenos[1:99], col = c(rep(mycol[1], 50),rep(mycol[2], 50)), bty="n", xlab = "PC1", ylab ="Sim phenos")
myl = lm(myPhenos[1:99]~ myEig$vectors[,1])
abline(myl)

```


3 populations

```{r 3pops, echo=T, eval=T}
#i=1
#x1 <- runif(1) #getting a random number so there's a seed
#save(".Random.seed", file=paste("data/figure_sims/randomSeed.",i, sep=""))
load('data/figure_sims/randomSeed.1')

npops=3
Faa = 0.15

sigma = matrix(0,nrow=3, ncol=3)
sigma[1:2,1:2] = matrix(Faa/2, nrow=2, ncol=2)
diag(sigma) = Faa
library(viridis)
heatmap(sigma, col = viridis(4))
sigma2 = matrix(0, nrow=9, ncol=9)

for (x in 0:2){
 sigma2[(1:3)+x*3,(1:3)+x*3] = sigma + sigma[x+1,x+1]
  }
sigma2[4:6,1:3] = 0.075
sigma2[1:3,4:6] = 0.075




#simulate allele freqs in pops at these loci
nloci = 500
ancPop = runif(nloci, min=0, max=1)
presentPops1 = sapply(ancPop, function(x){mvrnorm(n=1, mu = rep(x,npops*3), x*(1-x)*sigma2)})
presentPops = apply(presentPops1, c(1,2), myBound) #deal with numbers greater or less than 0 (the outer bounds are sticky)

#get the population genotypes
npop = 30
popGenos = lapply(1:(npops*3), function(x) getPopGenos(x, presentPops, npop)) #a list of elements, each is a population

#make a kinship matrix with the last 400 sites
myG = do.call(rbind, lapply(popGenos, function(x){x[,101:500]}))
myK = make_k(myG/2)
heatmap(myK)

myEig = eigen(myK)

mycol = lacroix_palette('Mango')
plot(myEig$values, lwd=2, bty="n", col = mycol[6], xlab = "PC", ylab = "Eigenvalue")

beetas = matrix(c(rnorm(100), rep(0, 400)), ncol=1, nrow=nloci) 
popPhenos = getPopPhenos(popGenos, beetas)

nind = npops*3*npop - 1
#myPhenos = unlist(popPhenosNoise)
myPhenos = unlist(popPhenos) - mean(unlist(popPhenos))
plot(myEig$vectors[,1], myPhenos[1:nind], col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)), bty="n", xlab = "PC1", ylab ="Sim phenos", lwd=2)
myl = lm(myPhenos[1:nind]~ myEig$vectors[,1])
abline(myl)


plot(myEig$vectors[,2], myPhenos[1:nind], col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)), bty="n", xlab = "PC1", ylab ="Sim phenos", lwd=2)
myl = lm(myPhenos[1:nind]~ myEig$vectors[,2])
abline(myl)


plot(myEig$vectors[,3], myPhenos[1:nind], col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)), bty="n", xlab = "PC1", ylab ="Sim phenos",lwd=2)
myl = lm(myPhenos[1:nind]~ myEig$vectors[,3])
abline(myl)


```


Now to show how we're estimating Va with the lower pcs

```{r}
## estimate Va with the loci and allele freqs
myPs =  colMeans(presentPops) #get allele freq across all pops (could do with anc pop too)
myVaGeno = calcVa(myPs, beetas)
myVaGeno

myVaAnc = calcVa(ancPop, beetas)
myVaAnc

#estimate Va with all PCs
myCs = sapply(1:nind, function(x){
  (myPhenos[1:nind] %*% myEig$vectors[,x])/sqrt(myEig$values[x])
}) #project traits onto PCs


myVaAll = var0(myCs[1:(nind-1)])
myVaAll 

#plot Va estimates
myVaPC = sapply(myCs[1:(nind-1)], var0)
#hist(myVaPC, col = mycol[4], border="white", main = "") ##this is the right distribution, right?

plot(myVaPC, bty="n", lwd=2, col = mycol[4], xlab = 'PC', ylab = "Va from one PC")
abline(h=myVaAll, col = mycol[3], lwd=2)
summary(myVaPC)

```


Do simulations
```{r sims, eval=F, include=F}
i=2

doSim <- function(i){
x1 <- runif(i) #getting a random number so there's a seed
save(".Random.seed", file=paste("data/figure_sims/randomSeed.",i, sep=""))

npops=3
Faa = 0.15

sigma = matrix(0,nrow=3, ncol=3)
sigma[1:2,1:2] = matrix(Faa/2, nrow=2, ncol=2)
diag(sigma) = Faa
sigma2 = matrix(0, nrow=9, ncol=9)

for (x in 0:2){
 sigma2[(1:3)+x*3,(1:3)+x*3] = sigma + sigma[x+1,x+1]
  }
sigma2[4:6,1:3] = 0.075
sigma2[1:3,4:6] = 0.075

#simulate allele freqs in pops at these loci
nloci = 500
nlocitrait = 100
ancPop = runif(nloci, min=0, max=1)
presentPops1 = sapply(ancPop, function(x){mvrnorm(n=1, mu = rep(x,npops*3), x*(1-x)*sigma2)})
presentPops = apply(presentPops1, c(1,2), myBound) #deal with numbers greater or less than 0 (the outer bounds are sticky)

#get the population genotypes
npop = 30
popGenos = lapply(1:(npops*3), function(x) getPopGenos(x, presentPops, npop)) #a list of elements, each is a population

#make a kinship matrix with the last 400 sites
myG = do.call(rbind, lapply(popGenos, function(x){x[,101:500]}))
myK = make_k(myG/2)

myEig = eigen(myK)

beetas = matrix(c(rnorm(nlocitrait), rep(0, nloci-nlocitrait)), ncol=1, nrow=nloci) 
popPhenos = getPopPhenos(popGenos, beetas)

myPhenos = unlist(popPhenos) - mean(unlist(popPhenos))

myPs =  colMeans(presentPops) #get allele freq across all pops (could do with anc 
myVaGeno = calcVa(myPs, beetas)
myVaAnc = calcVa(ancPop, beetas)

#estimate Va with all PCs
ninds = npops*npop*3 - 1
myCs = sapply(1:ninds, function(x){
  (myPhenos[1:ninds] %*% myEig$vectors[,x])/sqrt(myEig$values[x])
}) #project traits onto PCs


myVaAll = var0(myCs[1:(ninds-1)])
myVaPC = sapply(myCs[1:(ninds-1)], var0)

return(list(vapc = myVaPC, vaanc = myVaAnc, vageno = myVaGeno, vaall = myVaAll))
}

vaSims = sapply(2:202, doSim)
save(vaSims, file = "data/figure_sims/vaSimresults")
```

Look at sims
```{r simslook, eval=F, include=F}
load('data/figure_sims/vaSimresults')

#plot out the mean Va for each PC across all PCs, divided by what you'd get for total
allVaPCs = rowMeans(sapply(1:200, function(x){vaSims[,x]$vapc/vaSims[,x]$vaall}))

plot(allVaPCs)
plot(allVaPCs[1:50])
```

So what does the final figure look like??

```{r finalfigure, echo=T, eval=F}
#demonstration dendogram
#install.packages('dendextend')
library(dendextend)
nloci = 500
mycol = lacroix_palette('Lime')[c(2,5,6)]
ancPopd = runif(nloci, min=0, max=1)
presentPops3 = sapply(ancPop, function(x){mvrnorm(n=1, mu = rep(x,npops), x*(1-x)*sigma)})
dd = dist(presentPops3, method='euclidean')
hc = hclust(dd)
hcd = as.dendrogram(hc)
#nodePar <- list(lab.cex = 0.6, 19, pch = c(NA, 19),
                cex = 5, col = c('white',mycol))

myPhenos = unlist(popPhenos) - mean(unlist(popPhenos))

postscript("conceptfigure.eps",height=5,width=10,paper="special",horizontal=FALSE,colormodel="cymk")
#png('conceptfigure.png', height=250, width=500)
par(mfrow=c(1,4), mar = c(15,5,5,2), cex.lab = 1.5, cex.axis=1.5, xpd=T)

plot(rotate(hcd, c(3,2,1)), type="rectangle", leaflab = 'none', yaxt = "n", edgePar = c(lwd=3))
points(c(1,2,3), c(0,0,0), pch = 1, lwd=8, col = mycol, cex=5)

par(mar=c(5,5,5,2))

#heatmap(sigma, col = "white", rowv = NULL, labCol = "", labRow = "", Rowv= NA)



plot(-myEig$vectors[,1], myPhenos[1:nind], col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)), ylim = c(-20,30),bty="n", xlab = "PC 1", ylab ="Trait", lwd=2)
#myl = lm(myPhenos[1:nind]~ myEig$vectors[,1])
#legend('topleft', c('Pop 1','Pop 2','Pop 3'), fill = mycol, border="white", bty="n", cex=1.5)
mtext('A', side=3, adj=-0.1, cex=2, line=1)

#abline(myl, lwd=2, col = mycol[5])


plot(myEig$vectors[,2], myPhenos[1:nind],  col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)), bty="n", xlab = "PC 2", ylim = c(-20,30),bty="n", ylab ="Trait", lwd=2)
#myl = lm(myPhenos[1:nind]~ myEig$vectors[,2])
mtext('B', side=3, adj=-0.1, cex=2, line=1)

#abline(myl, lwd=2, col = mycol[5])


plot(myEig$vectors[,3], myPhenos[1:nind],  col = c(rep(mycol[1], 90),rep(mycol[2], 90), rep(mycol[3], 90)),  bty="n", xlab = "PC 3", ylab ="Trait",lwd=2,
ylim = c(-20,30),bty="n")
mtext('C', side=3, adj=-0.1, cex=2, line=1)

#abline(myl, lwd=2, col = mycol[5])


dev.off()
```

